language: csharp
mono: latest
dotnet: 2.1.201
sudo: false

git:
  depth: false

if: NOT branch =~ ^develop/.*$ OR branch =~ ^develop/travis/.*$

cache:
  directories:
  - packages
  - Demo/Service/packages
  - $HOME/.nuget

script:
  - dotnet restore ./dotnet-fake.fsproj
  - dotnet fake run ./Build/setup.fsx
  - dotnet fake run ./Build/build.fsx