language: csharp
mono: latest
dotnet: 2.1.4
dist: trusty
sudo: false
solution: AltCover.sln

git:
  depth: false

if: NOT branch =~ ^develop/.*$ OR branch =~ ^develop/travis/.*$

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

install:
  - nuget restore ./AltCover.sln
  - dotnet restore ./dotnet-fake.csproj

script:
  - dotnet fake run Build/prebuild.fsx
  - dotnet fake run Build/build.fsx

