language: csharp
mono: latest
dotnet: 2.1.300
dist: trusty
sudo: false
solution: AltCover.sln

git:
  depth: false

if: NOT branch =~ ^develop/.*$

install:
  - nuget restore ./AltCover.sln

script:
  - mono packages/FAKE.4.64.4/tools/FAKE.exe Build/prebuild.fsx
  - mono packages/FAKE.4.64.4/tools/FAKE.exe Build/build.fsx

