version: 0.1.{build}
branches:
  except:
  - /develop.*/
image: Visual Studio 2017
shallow_clone: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: qgIIfE76i59qTVO64mT7QwKcAUUYCQLie4XdUdlnt7MXLhrwqTbcfGUsCss/TmLg
cache: packages -> **\packages.config
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    .\Build\get-nuget.ps1

    .\fake.bat
test:
  assemblies:
    only:
    - _Binaries\AltCover.Tests\Debug+AnyCPU\*.dll
artifacts:
- path: _Packaging\*.nupkg
  name: NuGet
notifications:
- provider: Slack
  incoming_webhook: 
    secure: yzKiNN5snmI7Vzh12NWUEKC+V/w5wGI1ZMUGPT8p5WRefjAbB6DSgYkmWnzNADq9SurhbgIE2hlcCQivCQJ5gQE3AEGFpe+V7Dh/Up/jV0U=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false