version: 0.1.{build}
branches:
  except:
  - /develop.*/
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: qgIIfE76i59qTVO64mT7QwKcAUUYCQLie4XdUdlnt7MXLhrwqTbcfGUsCss/TmLg
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    .\Build\get-nuget.ps1

    .\fake.bat
test:
  assemblies:
    only:
    - _Binaries\AltCover.Tests\Debug+AnyCPU\*.dll
artifacts:
- path: _Packaging\*.nupkg
  name: NuGet